name: CI (Build)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Update version for ci
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          CURRENT_VERSION=$(grep -oP '^version = "\K[^\"]+' ./src/main/resources/META-INF/mods.toml)
          if [[ "$CURRENT_VERSION" =~ -alpha\.[0-9]+$ ]]; then
            BASE_VERSION=${CURRENT_VERSION%-alpha*}
            ALPHA_NUM=${CURRENT_VERSION##*-alpha.}
            NEW_ALPHA_NUM=$((ALPHA_NUM + 1))
            NEW_VERSION="${BASE_VERSION}-alpha.${NEW_ALPHA_NUM}"
          else
          NEW_VERSION="${CURRENT_VERSION}-alpha.0"
          fi
          sed -i "s/^version = \"$CURRENT_VERSION\"/version = \"$NEW_VERSION\"/" ./src/main/resources/META-INF/mods.toml
          echo "Updated Mods.toml version to $NEW_VERSION"
          echo "CURRENT_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: MadeInAbyss-${CURRENT_VERSION}-${COMMIT_HASH}
          path: build/libs/*.jar
